Config = Config or {}

Config.MinZOffset = 30
Config.RamsNeeded = 2
Config.UnownedBlips = false

Config.Houses = {}
Config.Targets = {}
Config.StashWeights = { -- Please follow by tiers!
	[1] = {
		maxweight = 1000000,
		slots = 50,
	}
}

Config.Furniture = {
	["sofas"] = {
		label = "沙發",
		items = {
			[1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["label"] = "舊沙發" },
			[2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["label"] = "三座沙發" },
			[3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["label"] = "舊椅子" },
			[4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["label"] = "舊三座沙發" },
			[5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["label"] = "舊條紋沙發" },
			[6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["label"] = "舊單人黃色沙發" },
			[7] = { ["object"] = "v_res_fh_sofa", ["price"] = 3700, ["label"] = "轉角沙發" },
			[8] = { ["object"] = "v_res_mp_sofa", ["price"] = 3700, ["label"] = "轉角沙發2" },
			[9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["label"] = "沙發1" },
			[10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["label"] = "沙發2" },
			[11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["label"] = "沙發3" },
			[12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["label"] = "沙發4" },
			[13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["label"] = "沙發5" },
			[14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["label"] = "沙發6" },
			[15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["label"] = "沙發7" },
			[16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["label"] = "沙發8" },
			[17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["label"] = "沙發9" },
			[18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["label"] = "沙發10" },
			[19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["label"] = "沙發11" },
			[20] = { ["object"] = "v_ilev_m_sofa", ["price"] = 2000, ["label"] = "白色沙發" },
			[21] = { ["object"] = "v_med_p_sofa", ["price"] = 1000, ["label"] = "皮革沙發（棕色）" },
			[22] = { ["object"] = "v_club_officesofa", ["price"] = 500, ["label"] = "窮人沙發紅色" },
			[23] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 1000, ["label"] = "黑色沙發" },
			[24] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 5000, ["label"] = "轉角沙發3" },
			[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 1000, ["label"] = "木質沙發" },
			[26] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 5000, ["label"] = "轉角沙發4" },
			[27] = { ["object"] = "apa_mp_h_yacht_sofa_02", ["price"] = 1000, ["label"] = "棕色沙發" },
			[28] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 5000, ["label"] = "白色長沙發" },
			[29] = { ["object"] = "prop_couch_01", ["price"] = 1000, ["label"] = "沙發坐墊" },
			[30] = { ["object"] = "prop_couch_03", ["price"] = 1000, ["label"] = "黃色沙發" },
			[31] = { ["object"] = "prop_couch_04", ["price"] = 1000, ["label"] = "皮革沙發坐墊" },
			[32] = { ["object"] = "prop_couch_lg_05", ["price"] = 500, ["label"] = "灯芯絨沙發" },
			[33] = { ["object"] = "prop_couch_lg_06", ["price"] = 1000, ["label"] = "皮革沙發（棕色）2" },
			[34] = { ["object"] = "prop_couch_lg_07", ["price"] = 1000, ["label"] = "沙發坐墊2" },
			[35] = { ["object"] = "prop_couch_lg_08", ["price"] = 1000, ["label"] = "皮革沙發（棕色）3" },
			[36] = { ["object"] = "prop_couch_sm1_07", ["price"] = 500, ["label"] = "皮革轉角沙發" },
			[37] = { ["object"] = "prop_couch_sm2_07", ["price"] = 500, ["label"] = "皮革直角沙發" },
			[38] = { ["object"] = "prop_couch_sm_06", ["price"] = 500, ["label"] = "小型皮革沙發" },
			[39] = { ["object"] = "apa_mp_h_stn_sofa2seat_02", ["price"] = 1000, ["label"] = "愛座椅" },
			[40] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 5000, ["label"] = "轉角沙發5" },
			[41] = { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 5000, ["label"] = "轉角沙發6" },
			[42] = { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 5000, ["label"] = "轉角沙發7" },
			[43] = { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 5000, ["label"] = "轉角沙發8" },
			[44] = { ["object"] = "apa_mp_h_stn_sofacorn_09", ["price"] = 5000, ["label"] = "轉角沙發9" },
			[45] = { ["object"] = "ex_mp_h_off_sofa_003", ["price"] = 1000, ["label"] = "藍色布沙發" },
			[46] = { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 1000, ["label"] = "白色皮革沙發" },
			[47] = { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 1000, ["label"] = "黑色皮革沙發" },
			[48] = { ["object"] = "hei_heist_stn_sofa2seat_03", ["price"] = 1000, ["label"] = "現代沙發" },
			[49] = { ["object"] = "hei_heist_stn_sofa2seat_06", ["price"] = 1000, ["label"] = "棕色沙發" },
			[50] = { ["object"] = "hei_heist_stn_sofa3seat_01", ["price"] = 1000, ["label"] = "躺椅" },
			[51] = { ["object"] = "hei_heist_stn_sofa3seat_02", ["price"] = 1000, ["label"] = "現代沙發2" },
			[52] = { ["object"] = "hei_heist_stn_sofa3seat_06", ["price"] = 1000, ["label"] = "現代沙發3" },
			[53] = { ["object"] = "imp_prop_impexp_sofabed_01a", ["price"] = 1000, ["label"] = "沙發床" },
			[54] = { ["object"] = "prop_t_sofa_02", ["price"] = 1000, ["label"] = "沙發床2" },
		},
	},
	["chairs"] = {
		label = "椅子",
		items = {
			[1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["label"] = "高椅" },
			[2] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 500, ["label"] = "條紋椅4" },
			[3] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["label"] = "椅子1" },
			[4] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["label"] = "椅子2" },
			[5] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["label"] = "高椅2" },
			[6] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["label"] = "廚房椅1" },
			[7] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["label"] = "廚房椅2" },
			[8] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["label"] = "廚房椅3" },
			[9] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["label"] = "椅子3" },
			[10] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["label"] = "椅子4" },
			[11] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["label"] = "高椅3" },
			[12] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["label"] = "扶手椅" },
			[13] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["label"] = "廚房椅4" },
			[14] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["label"] = "椅子5" },
			[15] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["label"] = "MB椅" },
			[16] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["label"] = "扶手椅2" },
			[17] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["label"] = "廚房椅5" },
			[18] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["label"] = "書房椅" },
			[19] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["label"] = "椅子框架" },
			[20] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["label"] = "椅子 5" },
			[21] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["label"] = "辦公椅" },
			[22] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["label"] = "椅子 6" },
			[23] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["label"] = "皮質椅子" },
			[24] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["label"] = "Scuz 椅子" },
			[25] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["label"] = "書桌椅" },
			[26] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["label"] = "輕鬆椅" },
			[27] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["label"] = "編織椅" },
			[28] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["label"] = "直椅" },
			[29] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["label"] = "直椅 2" },
			[30] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["label"] = "遊艇椅 1" },
			[31] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["label"] = "遊艇椅 2" },
			[32] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["label"] = "遊艇椅 3" },
			[33] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["label"] = "遊艇椅 4" },
			[34] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["label"] = "白色椅子" },
			[35] = { ["object"] = "v_ret_chair", ["price"] = 100, ["label"] = "椅子 7" },
			[36] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["label"] = "TA 椅子" },
			[37] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["label"] = "辦公椅 2" },
			[38] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 1000, ["label"] = "白色扶手椅" },
			[39] = { ["object"] = "v_club_barchair", ["price"] = 300, ["label"] = "椅子 8" },
			[40] = { ["object"] = "prop_off_chair_04", ["price"] = 300, ["label"] = "書桌椅 2" },
			[41] = { ["object"] = "v_club_stagechair", ["price"] = 500, ["label"] = "粉紅扶手椅" },
			[42] = { ["object"] = "v_club_officechair", ["price"] = 500, ["label"] = "書桌椅 3" },
			[43] = { ["object"] = "prop_armchair_01", ["price"] = 500, ["label"] = "坐椅" },
			[44] = { ["object"] = "prop_bar_stool_01", ["price"] = 300, ["label"] = "吧椅" },
			[45] = { ["object"] = "apa_mp_h_yacht_stool_01", ["price"] = 300, ["label"] = "白色腳凳" },
			[46] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 500, ["label"] = "Sitchair 3" },
			[47] = { ["object"] = "apa_mp_h_stn_chairstool_12", ["price"] = 300, ["label"] = "腳踏板" },
			[48] = { ["object"] = "prop_chair_03", ["price"] = 100, ["label"] = "木椅" },
			[49] = { ["object"] = "prop_couch_sm_05", ["price"] = 500, ["label"] = "灯芯绒扶手椅" },
			[50] = { ["object"] = "prop_couch_sm_07", ["price"] = 300, ["label"] = "白色扶手椅 2" },
			[51] = { ["object"] = "prop_couch_sm_02", ["price"] = 300, ["label"] = "橙色扶手椅" },
			[52] = { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 500, ["label"] = "躺椅" },
			[53] = { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 500, ["label"] = "躺椅 2" },
			[54] = { ["object"] = "apa_mp_h_din_chair_04", ["price"] = 500, ["label"] = "現代椅" },
			[55] = { ["object"] = "apa_mp_h_din_chair_08", ["price"] = 500, ["label"] = "現代椅 2" },
			[56] = { ["object"] = "apa_mp_h_din_chair_09", ["price"] = 500, ["label"] = "現代椅 3" },
			[57] = { ["object"] = "apa_mp_h_din_chair_12", ["price"] = 500, ["label"] = "現代椅 4" },
			[58] = { ["object"] = "apa_mp_h_din_stool_04", ["price"] = 500, ["label"] = "現代椅 5" },
			[59] = { ["object"] = "apa_mp_h_stn_chairarm_01", ["price"] = 500, ["label"] = "現代椅 6" },
			[60] = { ["object"] = "apa_mp_h_stn_chairarm_02", ["price"] = 500, ["label"] = "現代椅 7" },
			[61] = { ["object"] = "apa_mp_h_stn_chairarm_03", ["price"] = 500, ["label"] = "現代椅 8" },
			[62] = { ["object"] = "apa_mp_h_stn_chairarm_09", ["price"] = 500, ["label"] = "現代椅 9" },
			[63] = { ["object"] = "apa_mp_h_stn_chairarm_11", ["price"] = 500, ["label"] = "現代椅 10" },
			[64] = { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 500, ["label"] = "現代椅 11" },
			[65] = { ["object"] = "apa_mp_h_stn_chairarm_24", ["price"] = 500, ["label"] = "現代椅 12" },
			[66] = { ["object"] = "apa_mp_h_stn_chairarm_25", ["price"] = 500, ["label"] = "現代椅 13" },
			[67] = { ["object"] = "apa_mp_h_stn_chairarm_26", ["price"] = 500, ["label"] = "現代椅 14" },
			[68] = { ["object"] = "apa_mp_h_stn_chairstrip_04", ["price"] = 500, ["label"] = "現代椅 15" },
			[69] = { ["object"] = "apa_mp_h_stn_chairstrip_05", ["price"] = 500, ["label"] = "現代椅 16" },
			[70] = { ["object"] = "apa_mp_h_stn_chairstrip_08", ["price"] = 500, ["label"] = "現代椅 17" },
			[71] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 500, ["label"] = "腳凳" },
			[72] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 500, ["label"] = "腳凳 2" },
			[73] = { ["object"] = "apa_mp_h_yacht_barstool_01", ["price"] = 500, ["label"] = "吧椅 2" },
			[74] = { ["object"] = "ba_prop_int_glam_stool", ["price"] = 500, ["label"] = "吧椅 3" },
			[75] = { ["object"] = "ba_prop_battle_club_chair_01", ["price"] = 500, ["label"] = "辦公椅" },
			[76] = { ["object"] = "ba_prop_battle_club_chair_02", ["price"] = 500, ["label"] = "辦公椅 2" },
			[77] = { ["object"] = "ba_prop_battle_club_chair_03", ["price"] = 500, ["label"] = "辦公椅 3" },
			[78] = { ["object"] = "ba_prop_battle_control_seat", ["price"] = 500, ["label"] = "遊戲椅" },
		},
	},
	["beds"] = {
		label = "床",
		items = {
			[1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["label"] = "床 1" },
			[2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["label"] = "床 2" },
			[3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["label"] = "主臥床" },
			[4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["label"] = "次臥床" },
			[5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["label"] = "床 3" },
			[6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["label"] = "床 4" },
			[7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["label"] = "T形床" },
			[8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["label"] = "TT形床" },
			[9] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 5000, ["label"] = "精緻床" },
			[10] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 5000, ["label"] = "紅色床" },
			[11] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 3000, ["label"] = "方形床" },
			[12] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 3000, ["label"] = "現代床" },
			[13] = { ["object"] = "apa_mp_h_yacht_bed_01", ["price"] = 5000, ["label"] = "加州大床" },
			[14] = { ["object"] = "apa_mp_h_yacht_bed_02", ["price"] = 5000, ["label"] = "加州大床 2" },
			[15] = { ["object"] = "bkr_prop_biker_campbed_01", ["price"] = 100, ["label"] = "露營床" },
			[16] = { ["object"] = "ex_prop_exec_bed_01", ["price"] = 700, ["label"] = "小床" },
			[17] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 700, ["label"] = "小床 2" },
			[18] = { ["object"] = "p_mbbed_s", ["price"] = 700, ["label"] = "床 5" },
		},
	},
	["general"] = {
		label = "一般擺飾",
		items = {
			[1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["label"] = "豆袋椅 1" },
			[2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["label"] = "白花瓶" },
			[3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["label"] = "墊牆" },
			[4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["label"] = "物品" },
			[5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["label"] = "鞭子" },
			[6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["label"] = "雜誌" },
			[7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["label"] = "打開的雜誌" },
			[8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["label"] = "雜誌整理盒" },
			[9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["label"] = "瑜珈墊 1" },
			[10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["label"] = "瑜珈墊 2" },
			[11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["label"] = "剃鬚水盒" },
			[12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["label"] = "花朵" },
			[13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["label"] = "水果碗" },
			[14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["label"] = "洗衣籃" },
			[15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["label"] = "腳凳" },
			[16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["label"] = "雕塑" },
			[17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["label"] = "雜誌架" },
			[18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["label"] = "首飾盒" },
			[19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["label"] = "垃圾桶" },
			[20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["label"] = "華麗碗" },
			[21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["label"] = "青銅花瓶" },
			[22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["label"] = "粉筆板" },
			[23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["label"] = "梳妝台" },
			[24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["label"] = "底座" },
			[25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["label"] = "煙灰缸" },
			[26] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["label"] = "蠟燭" },
			[27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["label"] = "大蠟燭" },
			[28] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["label"] = "秤" },
			[29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["label"] = "床枕" },
			[30] = { ["object"] = "v_med_cor_whiteboard", ["price"] = 300, ["label"] = "白板" },
			[31] = { ["object"] = "prop_ashtray_01", ["price"] = 100, ["label"] = "黑色煙灰缸" },
			[32] = { ["object"] = "v_ret_fh_ashtray", ["price"] = 100, ["label"] = "石制煙灰缸" },
			[33] = { ["object"] = "v_24_wdr_mesh_rugs", ["price"] = 500, ["label"] = "地毯" },
			[34] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 500, ["label"] = "地毯 2" },
			[35] = { ["object"] = "ex_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "地毯 3" },
			[36] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 500, ["label"] = "地毯 4" },
			[37] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 500, ["label"] = "地毯 5" },
			[38] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 500, ["label"] = "地毯 6" },
			[39] = { ["object"] = "v_club_rack", ["price"] = 500, ["label"] = "衣架" },
		},	
	},
	["general2"] = {
		label = "物件",
		items = {
			[1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["label"] = "A4 堆疊" },
			[2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["label"] = "40 盎司" },
			[3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["label"] = "啤酒瓶" },
			[4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["label"] = "飛行員太陽眼鏡" },
			[5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["label"] = "細節桌" },
			[6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["label"] = "啤酒箱" },
			[7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["label"] = "雙筒望遠鏡" },
			[8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["label"] = "Blox 噴霧" },
			[9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["label"] = "邦戈鼓" },
			[10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["label"] = "水煙" },
			[11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["label"] = "Boombox 音響" },
			[12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["label"] = "碗裝薯片" },
			[13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["label"] = "糖果" },
			[14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["label"] = "手提袋" },
			[15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["label"] = "陶瓷罐" },
			[16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["label"] = "雪茄包 1" },
			[17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["label"] = "雪茄包 2" },
			[18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["label"] = "啤酒箱 2" },
			[19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["label"] = "文件夾" },
			[20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["label"] = "杯子" },
			[21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["label"] = "現金信封" },
			[22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["label"] = "香檳長笛" },
			[23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["label"] = "行李袋" },
			[24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["label"] = "DVD" },
			[25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["label"] = "DVD 盒" },
			[26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["label"] = "電影胶卷" },
			[27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["label"] = "百葉窗" },
			[28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["label"] = "袋子" },
			[29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["label"] = "熨衣板" },
			[30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["label"] = "武士刀" },
			[31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["label"] = "水壺" },
			[32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["label"] = "板條箱" },
			[33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["label"] = "汽油罐" },
			[34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["label"] = "麻袋" },
			[35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["label"] = "劇本瓶" },
			[36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["label"] = "劇本瓶 2" },
			[37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["label"] = "垃圾袋" },
			[38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["label"] = "威士忌瓶" },
			[39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["label"] = "水煙" },
			[40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["label"] = "花生碗" },
			[41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["label"] = "短杯" },
			[42] = { ["object"] = "prop_weed_bottle", ["price"] = 100, ["label"] = "大麻瓶" },
			[43] = { ["object"] = "p_cs_lighter_01", ["price"] = 100, ["label"] = "打火機" },
			[44] = { ["object"] = "p_cs_papers_01", ["price"] = 100, ["label"] = "捲煙紙" },
			[45] = { ["object"] = "v_res_d_dildo_f", ["price"] = 100, ["label"] = "黑色假陽具" },
			[46] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["label"] = "白色假陽具" },
			[47] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["label"] = "媽媽的玩具" },
			[48] = { ["object"] = "prop_champ_cool", ["price"] = 100, ["label"] = "香檳冰桶" },
			[49] = { ["object"] = "prop_champ_01b", ["price"] = 100, ["label"] = "香檳瓶" },
			[50] = { ["object"] = "prop_champ_flute", ["price"] = 100, ["label"] = "香檳杯" },
			[51] = { ["object"] = "ba_prop_club_champset", ["price"] = 300, ["label"] = "香檳套裝" },
			[52] = { ["object"] = "v_res_fa_candle01", ["price"] = 100, ["label"] = "藍色蠟燭" },
			[53] = { ["object"] = "v_res_fa_candle02", ["price"] = 100, ["label"] = "紅色蠟燭" },
			[54] = { ["object"] = "v_res_fa_candle03", ["price"] = 100, ["label"] = "黑色蠟燭" },
			[55] = { ["object"] = "v_res_fa_candle04", ["price"] = 100, ["label"] = "小蠟燭" },
			[56] = { ["object"] = "v_med_bottles2", ["price"] = 100, ["label"] = "化學品" },
			[57] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["label"] = "辦公用品" },
			[58] = { ["object"] = "v_med_p_notebook", ["price"] = 100, ["label"] = "筆記本" },
			[59] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["label"] = "大麻堆" },
			[60] = { ["object"] = "ba_prop_battle_trophy_battler", ["price"] = 100, ["label"] = "拳擊獎杯" },
			[61] = { ["object"] = "ba_prop_battle_trophy_no1", ["price"] = 100, ["label"] = "明星獎杯" },
			[62] = { ["object"] = "prop_golf_bag_01c", ["price"] = 100, ["label"] = "高爾夫袋" },
			[63] = { ["object"] = "hei_heist_kit_bin_01", ["price"] = 100, ["label"] = "垃圾桶" },
			[64] = { ["object"] = "prop_wooden_barrel", ["price"] = 100, ["label"] = "木桶" },
			[65] = { ["object"] = "bkr_prop_bkr_cash_scatter_01", ["price"] = 100, ["label"] = "分散的現金" },
			[66] = { ["object"] = "bkr_prop_bkr_cashpile_01", ["price"] = 100, ["label"] = "現金" },
			[67] = { ["object"] = "bkr_prop_bkr_cash_roll_01", ["price"] = 100, ["label"] = "捲現金" },
			[68] = { ["object"] = "bkr_prop_bkr_cashpile_04", ["price"] = 100, ["label"] = "一堆現金" },
			[69] = { ["object"] = "bkr_prop_weed_bigbag_open_01a", ["price"] = 100, ["label"] = "打開的大麻袋" },
			[70] = { ["object"] = "bkr_prop_weed_bigbag_02a", ["price"] = 100, ["label"] = "大麻袋 2" },
			[71] = { ["object"] = "bkr_prop_weed_bigbag_03a", ["price"] = 100, ["label"] = "大麻袋 3" },
			[72] = { ["object"] = "bkr_prop_weed_scales_01a", ["price"] = 100, ["label"] = "天平" },
			[73] = { ["object"] = "bkr_prop_weed_smallbag_01a", ["price"] = 100, ["label"] = "小袋子" },
			[74] = { ["object"] = "prop_gold_bar", ["price"] = 100, ["label"] = "金條" },
			[75] = { ["object"] = "beerrow_world", ["price"] = 100, ["label"] = "啤酒瓶" },
			[76] = { ["object"] = "beerrow_local", ["price"] = 100, ["label"] = "啤酒瓶 2" },
			[77] = { ["object"] = "p_cs_bbbat_01", ["price"] = 100, ["label"] = "球棒" },
			[78] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["label"] = "手銬" },
			[79] = { ["object"] = "p_cs_joint_02", ["price"] = 100, ["label"] = "大麻卷煙" },
			[80] = { ["object"] = "p_ing_coffeecup_01", ["price"] = 100, ["label"] = "咖啡杯" },
			[81] = { ["object"] = "p_tumbler_cs2_s", ["price"] = 100, ["label"] = "保溫杯" },
			[82] = { ["object"] = "prop_turkey_leg_01", ["price"] = 100, ["label"] = "火雞腿" },
			[83] = { ["object"] = "prop_amb_donut", ["price"] = 100, ["label"] = "甜甜圈" },
			[84] = { ["object"] = "prop_donut_02", ["price"] = 100, ["label"] = "甜甜圈 2" },
			[85] = { ["object"] = "prop_bar_shots", ["price"] = 100, ["label"] = "酒吧短槍" },
			[86] = { ["object"] = "prop_bar_stirrers", ["price"] = 100, ["label"] = "酒吧攪拌棒" },
			[87] = { ["object"] = "prop_beer_amopen", ["price"] = 100, ["label"] = "啤酒罐開啟" },
			[88] = { ["object"] = "prop_beer_blr", ["price"] = 100, ["label"] = "啤酒 1" },
			[89] = { ["object"] = "prop_beer_logger", ["price"] = 100, ["label"] = "啤酒 2" },
			[90] = { ["object"] = "prop_beer_stzopen", ["price"] = 100, ["label"] = "啤酒 3" },
			[91] = { ["object"] = "prop_bikerset", ["price"] = 100, ["label"] = "機車手套套裝" },
			[92] = { ["object"] = "prop_bottle_brandy", ["price"] = 100, ["label"] = "白蘭地酒瓶" },
			[93] = { ["object"] = "prop_tequila_bottle", ["price"] = 100, ["label"] = "龍舌蘭酒瓶" },
			[94] = { ["object"] = "prop_tequila", ["price"] = 100, ["label"] = "龍舌蘭酒" },
			[95] = { ["object"] = "prop_bottle_cognac", ["price"] = 100, ["label"] = "干邑酒瓶" },
			[96] = { ["object"] = "prop_bottle_macbeth", ["price"] = 100, ["label"] = "馬克白威士忌瓶" },
			[97] = { ["object"] = "prop_brandy_glass", ["price"] = 100, ["label"] = "白蘭地杯" },
			[98] = { ["object"] = "prop_mug_01", ["price"] = 100, ["label"] = "馬克杯 1" },
			[99] = { ["object"] = "prop_mug_02", ["price"] = 100, ["label"] = "馬克杯 2" },
			[100] = { ["object"] = "prop_mug_03", ["price"] = 100, ["label"] = "馬克杯 3" },
			[101] = { ["object"] = "prop_optic_vodka", ["price"] = 100, ["label"] = "伏特加" },
			[102] = { ["object"] = "prop_optic_jd", ["price"] = 100, ["label"] = "傑克丹尼" },
			[103] = { ["object"] = "prop_pint_glass_01", ["price"] = 100, ["label"] = "品特杯" },
			[104] = { ["object"] = "prop_pizza_box_03", ["price"] = 100, ["label"] = "比薩盒" },
			[105] = { ["object"] = "prop_sandwich_01", ["price"] = 100, ["label"] = "三明治" },
			[106] = { ["object"] = "prop_cava", ["price"] = 100, ["label"] = "香檳" },
			[107] = { ["object"] = "prop_drink_redwine", ["price"] = 100, ["label"] = "紅酒" },
			[108] = { ["object"] = "vodkarow", ["price"] = 100, ["label"] = "伏特加列" },
			[109] = { ["object"] = "prop_cherenkov_02", ["price"] = 100, ["label"] = "切連科夫" },
			[110] = { ["object"] = "prop_cherenkov_03", ["price"] = 100, ["label"] = "切連科夫 2" },
			[111] = { ["object"] = "prop_cocktail_glass", ["price"] = 100, ["label"] = "雞尾酒杯" },
			[112] = { ["object"] = "prop_cs_bottle_opener", ["price"] = 100, ["label"] = "瓶子開啟器" },
			[113] = { ["object"] = "prop_food_bs_chips", ["price"] = 100, ["label"] = "洋芋片" },
			[114] = { ["object"] = "prop_cs_burger_01", ["price"] = 100, ["label"] = "漢堡" },
			[115] = { ["object"] = "prop_cs_hand_radio", ["price"] = 100, ["label"] = "手持收音機" },
			[116] = { ["object"] = "prop_cs_hotdog_01", ["price"] = 100, ["label"] = "熱狗" },
			[117] = { ["object"] = "prop_cs_milk_01", ["price"] = 100, ["label"] = "牛奶" },
			[118] = { ["object"] = "prop_cs_panties", ["price"] = 100, ["label"] = "內褲" },
			[119] = { ["object"] = "prop_cs_steak", ["price"] = 100, ["label"] = "肉" }
		},
	},
	["general3"] = {
		label = "隨機",
		items = {			
			[1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["label"] = "回收桶" },
			[2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["label"] = "籃子" },
			[3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["label"] = "購物袋 1" },
			[4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["label"] = "購物袋 2" },
			[5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["label"] = "垃圾桶" },
			[6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["label"] = "收銀機" },
			[7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["label"] = "椅子 01" },
			[8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["label"] = "椅子 02" },
			[9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["label"] = "時鐘" },
			[10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["label"] = "產品 1" },
			[11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["label"] = "產品 2" },
			[12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["label"] = "產品 3" },
			[13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["label"] = "產品 4" },
			[14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["label"] = "產品 5" },
			[15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["label"] = "產品 6" },
			[16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["label"] = "HD 單元 1" },
			[17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["label"] = "HD 單元 2" },
			[18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["label"] = "冰箱" },
			[19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["label"] = "袋子 1" },
			[20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["label"] = "袋子 2" },
			[21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["label"] = "書 1" },
			[22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["label"] = "書 2" },
			[23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["label"] = "書 3" },
			[24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["label"] = "書 4" },
			[25] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["label"] = "攝影機" },
			[26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["label"] = "急救包" },
			[27] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["label"] = "英雄" },
			[28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["label"] = "雜誌 1" },
			[29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["label"] = "雜誌 2" },
			[30] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["label"] = "頭骨" },
			[31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["label"] = "吉他" },
			[32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["label"] = "手提包" },
			[33] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["label"] = "公事包" },
			[34] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["label"] = "大袋子" },
			[35] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["label"] = "骨鋸" },
			[36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["label"] = "化肥" },
			[37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["label"] = "購物袋" },
			[38] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["label"] = "小瓶" },
			[39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["label"] = "布娃娃" },
			[40] = { ["object"] = "v_res_fa_book03", ["price"] = 100, ["label"] = "古老的書" },
			[41] = { ["object"] = "prop_weight_rack_02", ["price"] = 500, ["label"] = "啞鈴架" },
			[42] = { ["object"] = "prop_weight_bench_02", ["price"] = 500, ["label"] = "沙發啞鈴組" },
			[43] = { ["object"] = "prop_tool_broom", ["price"] = 100, ["label"] = "掃帚" },
			[44] = { ["object"] = "prop_fire_exting_2a", ["price"] = 100, ["label"] = "滅火器" },
			[45] = { ["object"] = "v_res_vacuum", ["price"] = 100, ["label"] = "吸塵器" },
			[46] = { ["object"] = "v_ret_gc_fan", ["price"] = 100, ["label"] = "風扇" },
			[47] = { ["object"] = "prop_paint_stepl01b", ["price"] = 100, ["label"] = "梯子" },
			[48] = { ["object"] = "bkr_prop_weed_bucket_01b", ["price"] = 100, ["label"] = "肥料" },
			[49] = { ["object"] = "v_club_vusnaketank", ["price"] = 500, ["label"] = "玻璃箱" },
			[50] = { ["object"] = "prop_pooltable_02", ["price"] = 1500, ["label"] = "撞球桌" },
			[51] = { ["object"] = "prop_pool_rack_02", ["price"] = 100, ["label"] = "撞球桿" },
			[52] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ 音樂設備" },
			[53] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "伺服器機架" },
		},
	},
	["general4"] = {
		label = "隨機 2",
		items = {
			[1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["label"] = "充氣娃娃" },
			[2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["label"] = "蛋型時鐘" },
			[3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["label"] = "電吉他 1" },
			[4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["label"] = "電吉他 2" },
			[5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["label"] = "電吉他 3" },
			[6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["label"] = "飼料袋" },
			[7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["label"] = "地板掃把" },
			[8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["label"] = "水果籃" },
			[9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["label"] = "拂塵器" },
			[10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["label"] = "葡萄" },
			[11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["label"] = "飯店時鐘" },
			[12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["label"] = "偶像盒" },
			[13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["label"] = "珠寶" },
			[14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["label"] = "珠寶" },
			[15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["label"] = "珠寶" },
			[16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["label"] = "珠寶" },
			[17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["label"] = "珠寶" },
			[18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["label"] = "珠寶" },
			[19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["label"] = "珠寶" },
			[20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["label"] = "陳列盤" },
			[21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["label"] = "陳列盤" },
			[22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["label"] = "陳列盤" },
			[23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["label"] = "陳列盤" },
			[24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["label"] = "陳列盤" },
			[25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["label"] = "陳列盤" },
			[26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["label"] = "陳列盤" },
			[27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["label"] = "陳列盤" },
			[28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["label"] = "綠幕" },
			[29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["label"] = "手提包" },
			[30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["label"] = "傑瑞罐" },
			[31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["label"] = "鍵盤 1" },
			[32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["label"] = "鍵盤 2" },
			[33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["label"] = "手提箱 1" },
			[34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["label"] = "手提箱 2" },
			[35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["label"] = "手提箱 3" },
			[36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["label"] = "覆盆子清潔劑" },
			[37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["label"] = "紙袋" },
			[38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["label"] = "購物袋" },
			[39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["label"] = "購物袋 2" },
			[40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["label"] = "瑜伽墊 1" },
			[41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["label"] = "瑜伽墊 2" },
			[42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["label"] = "瑜伽墊 3" },
			[43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["label"] = "薩克斯風" },
			[44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["label"] = "足球" },
			[45] = { ["object"] = "p_watch_01", ["price"] = 100, ["label"] = "手錶 1" },
			[46] = { ["object"] = "p_watch_02", ["price"] = 100, ["label"] = "手錶 2" },
			[47] = { ["object"] = "p_watch_03", ["price"] = 100, ["label"] = "手錶 3" },
			[48] = { ["object"] = "p_watch_04", ["price"] = 100, ["label"] = "手錶 4" },
			[49] = { ["object"] = "p_watch_05", ["price"] = 100, ["label"] = "手錶 5" },
			[50] = { ["object"] = "p_watch_06", ["price"] = 100, ["label"] = "手錶 6" },
			[51] = { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 100, ["label"] = "蠟燭" },
			[52] = { ["object"] = "apa_mp_h_acc_candles_02", ["price"] = 100, ["label"] = "蠟燭 2" },
			[53] = { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 100, ["label"] = "蠟燭 3" },
			[54] = { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 100, ["label"] = "蠟燭 4" },
			[55] = { ["object"] = "apa_mp_h_acc_fruitbowl_02", ["price"] = 100, ["label"] = "水果碗" },
			[56] = { ["object"] = "apa_mp_h_acc_tray_01", ["price"] = 100, ["label"] = "雜物" },
			[57] = { ["object"] = "prop_bskball_01", ["price"] = 100, ["label"] = "籃球" },
			[58] = { ["object"] = "prop_cs_wrench", ["price"] = 100, ["label"] = "板手" },
			[59] = { ["object"] = "prop_cs_bowie_knife", ["price"] = 100, ["label"] = "鮑伊刀" },
			[60] = { ["object"] = "prop_w_me_hatchet", ["price"] = 100, ["label"] = "短柄斧" },
		},
	},
	["small"] = {
		label = "精細物件",
		items = {
			[1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["label"] = "貓雕塑" },
			[2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["label"] = "小丑雕塑" },
			[3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["label"] = "權威雕塑" },
			[4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["label"] = "女性雕塑" },
			[5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["label"] = "佛朗明哥雕塑" },
			[6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["label"] = "女孩雕塑" },
			[7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["label"] = "女孩小丑雕塑" },
			[8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["label"] = "方尖碑雕塑" },
			[9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["label"] = "柱子雕塑" },
			[10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["label"] = "茶壺" },
			[11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["label"] = "雕塑 1" },
			[12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["label"] = "雕塑 2" },
			[13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["label"] = "雕塑 3" },
			[14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["label"] = "雕塑 4" },
			[15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["label"] = "滑板" },
			[16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["label"] = "素描本" },
			[17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["label"] = "面紙" },
			[18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["label"] = "籃子" },
			[19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["label"] = "垃圾桶" },
			[20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["label"] = "坐墊 1" },
			[21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["label"] = "坐墊 2" },
			[22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["label"] = "坐墊 3" },
			[23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["label"] = "坐墊 4" },
			[24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["label"] = "坐墊 5" },
			[25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["label"] = "坐墊 6" },
			[26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["label"] = "水果碗" },
			[27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["label"] = "櫃檯" },
			[28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["label"] = "偶像 1" },
			[29] = { ["object"] = "v_res_r_fighorsestnd", ["price"] = 300, ["label"] = "馬雕像（黑色）" },
			[30] = { ["object"] = "v_res_r_fighorse", ["price"] = 300, ["label"] = "馬雕像（大）" },
			[31] = { ["object"] = "v_res_r_figdancer", ["price"] = 300, ["label"] = "舞者雕像" },
			[32] = { ["object"] = "v_res_fa_idol02", ["price"] = 300, ["label"] = "大象雕像" },
			[33] = { ["object"] = "v_res_m_statue", ["price"] = 300, ["label"] = "雕塑" },
			[34] = { ["object"] = "v_20_ornaeagle", ["price"] = 300, ["label"] = "雕像（鷹）" },
			[35] = { ["object"] = "v_med_p_vaseround", ["price"] = 300, ["label"] = "花瓶（圓形）" },
			[36] = { ["object"] = "ex_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "花瓶（紫色）" },
			[37] = { ["object"] = "apa_mp_h_acc_dec_head_01", ["price"] = 300, ["label"] = "藝術品" },
			[38] = { ["object"] = "apa_mp_h_acc_dec_sculpt_02", ["price"] = 300, ["label"] = "藝術品 2" },
			[39] = { ["object"] = "ex_mp_h_acc_dec_plate_02", ["price"] = 300, ["label"] = "藝術品 3" },
			[40] = { ["object"] = "apa_mp_h_acc_bowl_ceramic_01", ["price"] = 300, ["label"] = "碗" },
			[41] = { ["object"] = "apa_mp_h_acc_dec_plate_01", ["price"] = 300, ["label"] = "秤 2" },
			[42] = { ["object"] = "apa_mp_h_acc_vase_01", ["price"] = 300, ["label"] = "花瓶（黑白）" },
			[43] = { ["object"] = "apa_mp_h_acc_vase_02", ["price"] = 300, ["label"] = "花瓶（紅色）" },
			[44] = { ["object"] = "apa_mp_h_acc_vase_05", ["price"] = 300, ["label"] = "花瓶" },
			[45] = { ["object"] = "apa_mp_h_acc_vase_06", ["price"] = 300, ["label"] = "花瓶（黑白） 2" },
		},
	},
	["storage"] = {
		label = "櫃子",
		items = {
			[1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["label"] = "大型櫥櫃" },
			[2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["label"] = "梳妝台" },
			[3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["label"] = "側櫃" },
			[4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["label"] = "側櫃" },
			[5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["label"] = "側櫃" },
			[6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["label"] = "床邊櫃" },
			[7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["label"] = "電視櫃" },
			[8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["label"] = "梳妝櫃" },
			[9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["label"] = "腳凳櫃" },
			[10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["label"] = "控制台櫃" },
			[11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["label"] = "櫥櫃" },
			[12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["label"] = "箱櫃" },
			[13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["label"] = "梅森櫃" },
			[14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["label"] = "衣櫃" },
			[15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["label"] = "側櫃" },
			[16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["label"] = "書桌" },
			[17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["label"] = "側櫃" },
			[18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["label"] = "側櫃 2" },
			[19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["label"] = "書櫃" },
			[20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["label"] = "儲物箱" },
			[21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["label"] = "儲物櫃" },
			[22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["label"] = "衣櫃" },
			[23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["label"] = "木櫃" },
			[24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["label"] = "豆袋椅 1" },
			[25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["label"] = "軍用箱 1" },
			[26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["label"] = "軍用箱 2" },
			[27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["label"] = "保險箱" },
			[28] = { ["object"] = "prop_toolchest_05", ["price"] = 5000, ["label"] = "工作臺" },
			[29] = { ["object"] = "v_corp_filecablow", ["price"] = 500, ["label"] = "低文件櫃" },
			[30] = { ["object"] = "v_corp_filecabtall", ["price"] = 500, ["label"] = "高文件櫃" },
			[31] = { ["object"] = "apa_mp_h_str_shelffloorm_02", ["price"] = 500, ["label"] = "大型現代櫥櫃" },
			[32] = { ["object"] = "v_ilev_frnkwarddr1", ["price"] = 500, ["label"] = "富蘭克林櫥櫃" },
			[33] = { ["object"] = "prop_coathook_01", ["price"] = 100, ["label"] = "衣帽架" },
			[34] = { ["object"] = "v_corp_lowcabdark01", ["price"] = 500, ["label"] = "低黑色文件櫃" },
			[35] = { ["object"] = "v_corp_tallcabdark01", ["price"] = 500, ["label"] = "高黑色文件櫃" },
			[36] = { ["object"] = "v_corp_cabshelves01", ["price"] = 1000, ["label"] = "黑色文件櫃" },
			[37] = { ["object"] = "v_corp_offshelf", ["price"] = 1000, ["label"] = "大文件櫃" },
			[38] = { ["object"] = "v_61_lng_mesh_unitc", ["price"] = 500, ["label"] = "白色書櫃" },
			[39] = { ["object"] = "ba_wardrobe", ["price"] = 500, ["label"] = "衣櫃" },
			[40] = { ["object"] = "apa_mp_h_str_sideboardl_06", ["price"] = 750, ["label"] = "現代櫥櫃" },
			[41] = { ["object"] = "apa_mp_h_str_sideboardl_09", ["price"] = 750, ["label"] = "現代櫥櫃 2" },
			[42] = { ["object"] = "apa_mp_h_str_shelfwallm_01", ["price"] = 750, ["label"] = "書櫃 2" },
			[43] = { ["object"] = "apa_mp_h_str_sideboardl_11", ["price"] = 750, ["label"] = "現代櫥櫃 3" },
			[44] = { ["object"] = "imp_prop_impexp_parts_rack_03a", ["price"] = 750, ["label"] = "車零件" },
			[45] = { ["object"] = "imp_prop_impexp_parts_rack_04a", ["price"] = 750, ["label"] = "車零件 2" },
			[46] = { ["object"] = "imp_prop_impexp_parts_rack_05a", ["price"] = 750, ["label"] = "車零件 3" },
			[47] = { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 750, ["label"] = "抽屜櫃" },
			[48] = { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 750, ["label"] = "抽屜櫃 2" },
			[49] = { ["object"] = "prop_rub_cabinet", ["price"] = 50, ["label"] = "生鏽文件櫃" },
			[50] = { ["object"] = "prop_tv_cabinet_03", ["price"] = 750, ["label"] = "小電視櫃" },
			[51] = { ["object"] = "prop_tv_cabinet_04", ["price"] = 750, ["label"] = "小電視櫃 2" },
			[52] = { ["object"] = "prop_tv_cabinet_05", ["price"] = 750, ["label"] = "小電視櫃 3" },
			[53] = { ["object"] = "apa_mp_h_str_shelffreel_01", ["price"] = 750, ["label"] = "宜家壁櫥" },
			[54] = { ["object"] = "apa_mp_h_str_sideboardl_13", ["price"] = 750, ["label"] = "現代櫥櫃 4" },
			[55] = { ["object"] = "apa_mp_h_str_sideboardl_14", ["price"] = 750, ["label"] = "現代櫥櫃 5" },
			[56] = { ["object"] = "apa_mp_h_str_sideboardm_02", ["price"] = 750, ["label"] = "現代櫥櫃 6" },
			[57] = { ["object"] = "bkr_prop_biker_garage_locker_01", ["price"] = 750, ["label"] = "摩托車儲物櫃" },
			[58] = { ["object"] = "gr_prop_gr_bench_04b", ["price"] = 750, ["label"] = "摩托車長椅" },
		},
	},
	["electronics"] = {
		label = "電力物品",
		items = {
			[1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["label"] = "舊冰箱" },
			[2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["label"] = "揚聲器" },
			[3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["label"] = "揚聲器底座" },
			[4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["label"] = "床頭鐘" },
			[5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["label"] = "電話" },
			[6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["label"] = "塔扇" },
			[7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["label"] = "風扇" },
			[8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["label"] = "大屏幕" },
			[9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["label"] = "顯示器" },
			[10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["label"] = "攪拌機" },
			[11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["label"] = "閉路電視" },
			[12] = { ["object"] = "prop_ld_lap_top", ["price"] = 100, ["label"] = "筆記型電腦" },
			[13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["label"] = "顯示器" },
			[14] = { ["object"] = "prop_speaker_05", ["price"] = 500, ["label"] = "掛式揚聲器" },
			[15] = { ["object"] = "prop_tv_flat_03b", ["price"] = 1000, ["label"] = "小型平面電視" },
			[16] = { ["object"] = "prop_laptop_01a", ["price"] = 750, ["label"] = "開啟的筆記型電腦" },
			[17] = { ["object"] = "prop_tv_flat_michael", ["price"] = 3000, ["label"] = "懸掛式平面電視" },
			[18] = { ["object"] = "prop_dyn_pc", ["price"] = 1000, ["label"] = "個人電腦" },
			[19] = { ["object"] = "prop_keyboard_01b", ["price"] = 100, ["label"] = "鍵盤" },
			[20] = { ["object"] = "prop_mouse_01b", ["price"] = 100, ["label"] = "電腦滑鼠" },
			[21] = { ["object"] = "v_ret_gc_phone", ["price"] = 100, ["label"] = "辦公電話" },
			[22] = { ["object"] = "prop_tv_flat_01", ["price"] = 5000, ["label"] = "大型平面電視" },
			[23] = { ["object"] = "prop_arcade_01", ["price"] = 5000, ["label"] = "電玩遊戲機" },
			[24] = { ["object"] = "prop_console_01", ["price"] = 250, ["label"] = "遊戲主機" },
			[25] = { ["object"] = "v_res_tre_dvdplayer", ["price"] = 250, ["label"] = "DVD 播放器" },
			[26] = { ["object"] = "prop_speaker_08", ["price"] = 500, ["label"] = "木製揚聲器" },
			[27] = { ["object"] = "prop_cctv_mon_02", ["price"] = 300, ["label"] = "閉路電視監視器" },
			[28] = { ["object"] = "prop_tv_flat_02", ["price"] = 2500, ["label"] = "站立式平面電視" },
			[29] = { ["object"] = "prop_cctv_cam_01a", ["price"] = 300, ["label"] = "閉路電視 2" },
			[30] = { ["object"] = "prop_dest_cctv_02", ["price"] = 300, ["label"] = "閉路電視監視器 2" },
			[31] = { ["object"] = "prop_cctv_cam_07a", ["price"] = 300, ["label"] = "閉路電視 3" },
			[32] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "平面電視家具" },
			[33] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 5500, ["label"] = "平面電視家具 2" },
			[34] = { ["object"] = "v_club_vu_deckcase", ["price"] = 1000, ["label"] = "DJ 設備" },
			[35] = { ["object"] = "v_corp_servercln", ["price"] = 1000, ["label"] = "伺服器架" },
			[36] = { ["object"] = "apa_mp_h_str_avunitl_01_b", ["price"] = 5500, ["label"] = "平面電視家具 3" },
			[37] = { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 5500, ["label"] = "平面電視家具 4" },
			[38] = { ["object"] = "apa_mp_h_str_avunitm_01", ["price"] = 5500, ["label"] = "平面電視家具 5" },
			[39] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 5500, ["label"] = "平面電視家具 6" },
			[40] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 5500, ["label"] = "平面電視家具 7" },
			[41] = { ["object"] = "v_res_printer", ["price"] = 300, ["label"] = "印表機" },
			[42] = { ["object"] = "apa_mp_h_acc_phone_01", ["price"] = 100, ["label"] = "老式電話" },
			[43] = { ["object"] = "v_res_mousemat", ["price"] = 300, ["label"] = "滑鼠墊" },
			[44] = { ["object"] = "v_res_pcheadset", ["price"] = 300, ["label"] = "耳機" },
			[45] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "電腦揚聲器" },
			[46] = { ["object"] = "ba_prop_battle_club_speaker_small", ["price"] = 500, ["label"] = "小音箱" },
			[47] = { ["object"] = "ba_prop_battle_club_speaker_med", ["price"] = 750, ["label"] = "音箱" },
			[48] = { ["object"] = "ba_prop_battle_club_speaker_large", ["price"] = 1000, ["label"] = "大音箱" },
			[49] = { ["object"] = "v_res_pcspeaker", ["price"] = 300, ["label"] = "電腦揚聲器" },
			[50] = { ["object"] = "v_res_pcwoofer", ["price"] = 300, ["label"] = "電腦低音炮" },
			[51] = { ["object"] = "prop_controller_01", ["price"] = 300, ["label"] = "遊戲手把" },
			[52] = { ["object"] = "prop_cs_remote_01", ["price"] = 300, ["label"] = "遙控器" },
			[53] = { ["object"] = "prop_portable_hifi_01", ["price"] = 300, ["label"] = "收音機" },
			[54] = { ["object"] = "prop_dj_deck_02", ["price"] = 300, ["label"] = "DJ 桌" },
			[55] = { ["object"] = "prop_speaker_01", ["price"] = 300, ["label"] = "揚聲器" },
		},
	},
	["lighting"] = {
		label = "照明",
		items = {
			[1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["label"] = "辦公桌公司燈" },
			[2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["label"] = "辦公桌燈" },
			[3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["label"] = "燈 AA" },
			[4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["label"] = "燈 1" },
			[5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["label"] = "地燈" },
			[6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["label"] = "燈 2" },
			[7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["label"] = "桌上燈" },
			[8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["label"] = "桌上燈 2" },
			[9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["label"] = "床頭燈" },
			[10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["label"] = "植物舌燈" },
			[11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["label"] = "桌上燈 3" },
			[12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["label"] = "燈架" },
			[13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["label"] = "燈架 2" },
			[14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["label"] = "桌上燈 4" },
			[15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["label"] = "風扇燈" },
			[16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["label"] = "高燈" },
			[17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["label"] = "壁燈" },
			[18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["label"] = "GC 燈" },
			[19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["label"] = "閃爍的燈光" },
			[20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["label"] = "側牆燈" },
			[21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["label"] = "測試燈" },
			[22] = { ["object"] = "prop_wall_light_07a", ["price"] = 100, ["label"] = "街燈" },
			[23] = { ["object"] = "prop_wall_light_01a", ["price"] = 100, ["label"] = "便宜燈" },
			[24] = { ["object"] = "v_serv_tu_light2_", ["price"] = 100, ["label"] = "工業風燈" },
			[25] = { ["object"] = "v_serv_tu_light3_", ["price"] = 100, ["label"] = "工業風燈 2" },
			[26] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 300, ["label"] = "吊燈" },
			[27] = { ["object"] = "v_med_p_floorlamp", ["price"] = 300, ["label"] = "大燈" },
			[28] = { ["object"] = "v_club_vu_lamp", ["price"] = 100, ["label"] = "小燈" },
			[29] = { ["object"] = "ba_prop_battle_lights_wall_l_a", ["price"] = 100, ["label"] = "壁燈" },
			[30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 300, ["label"] = "吊燈 2" },
			[31] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 300, ["label"] = "吊燈 3" },
			[32] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["label"] = "壁燈 2" },
			[33] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["label"] = "壁燈 3" },
			[34] = { ["object"] = "hei_heist_lit_lightpendant_02", ["price"] = 300, ["label"] = "吊燈 3" },
			[35] = { ["object"] = "prop_oldlight_01b", ["price"] = 100, ["label"] = "壁燈 4" },
			[36] = { ["object"] = "apa_mp_h_lit_floorlampnight_07", ["price"] = 100, ["label"] = "藍燈" },
			[37] = { ["object"] = "apa_mp_h_ceiling_light_01", ["price"] = 100, ["label"] = "商業燈" },
			[38] = { ["object"] = "apa_mp_h_ceiling_light_01_day", ["price"] = 100, ["label"] = "商業燈 2" },
			[39] = { ["object"] = "apa_mp_h_ceiling_light_02", ["price"] = 100, ["label"] = "吊燈" },
			[40] = { ["object"] = "apa_mp_h_ceiling_light_02_day", ["price"] = 100, ["label"] = "吊燈 2" },
			[41] = { ["object"] = "ba_prop_battle_lights_ceiling_l_d", ["price"] = 100, ["label"] = "商業燈 3" },
			[42] = { ["object"] = "ba_prop_battle_lights_ceiling_l_f", ["price"] = 100, ["label"] = "吊燈 3" },
			[43] = { ["object"] = "ba_prop_battle_lights_ceiling_l_e", ["price"] = 100, ["label"] = "吊燈 4" },
			[44] = { ["object"] = "apa_mp_h_floorlamp_a", ["price"] = 100, ["label"] = "地燈" },
			[45] = { ["object"] = "apa_mp_h_floorlamp_b", ["price"] = 100, ["label"] = "地燈 2" },
			[46] = { ["object"] = "apa_mp_h_floorlamp_c", ["price"] = 100, ["label"] = "地燈 3" },
			[47] = { ["object"] = "apa_mp_h_floor_lamp_int_08", ["price"] = 100, ["label"] = "地燈 4" },
			[48] = { ["object"] = "apa_mp_h_lampbulb_multiple_a", ["price"] = 100, ["label"] = "吊燈 5" },
			[49] = { ["object"] = "apa_mp_h_lit_floorlamp_02", ["price"] = 100, ["label"] = "地燈 5" },
			[50] = { ["object"] = "apa_mp_h_lit_floorlampnight_14", ["price"] = 100, ["label"] = "地燈 6" },
			[51] = { ["object"] = "apa_mp_h_lit_floorlamp_03", ["price"] = 100, ["label"] = "地燈 7" },
			[52] = { ["object"] = "apa_mp_h_lit_floorlamp_06", ["price"] = 100, ["label"] = "地燈 8" },
			[53] = { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["label"] = "地燈 9" },
			[54] = { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["label"] = "地燈 10" },
			[55] = { ["object"] = "apa_mp_h_lit_floorlamp_17", ["price"] = 100, ["label"] = "地燈 11" },
			[56] = { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["label"] = "夜燈" },
			[57] = { ["object"] = "apa_mp_h_lit_lamptablenight_24", ["price"] = 100, ["label"] = "夜燈 2" },
			[58] = { ["object"] = "apa_mp_h_lit_lamptable_005", ["price"] = 100, ["label"] = "夜燈 3" },
			[59] = { ["object"] = "apa_mp_h_lit_lamptable_04", ["price"] = 100, ["label"] = "夜燈 4" },
			[60] = { ["object"] = "apa_mp_h_lit_lamptable_09", ["price"] = 100, ["label"] = "夜燈 5" },
			[61] = { ["object"] = "apa_mp_h_lit_lamptable_14", ["price"] = 100, ["label"] = "夜燈 6" },
			[62] = { ["object"] = "apa_mp_h_lit_lamptable_17", ["price"] = 100, ["label"] = "夜燈 7" },
			[63] = { ["object"] = "apa_mp_h_yacht_table_lamp_01", ["price"] = 100, ["label"] = "夜燈 8" },
		},
	},
	["tables"] = {
		label = "桌子",
		items = {
			[1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["label"] = "咖啡桌 1" },
			[2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["label"] = "圓桌" },
			[3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["label"] = "小邊桌" },
			[4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["label"] = "桌子 A" },
			[5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["label"] = "桌子 B" },
			[6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["label"] = "桌子 C" },
			[7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["label"] = "餐桌" },
			[8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["label"] = "咖啡桌 2" },
			[9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["label"] = "低桌" },
			[10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["label"] = "床邊桌" },
			[11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["label"] = "書桌" },
			[12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["label"] = "邊桌" },
			[13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["label"] = "控制台桌" },
			[14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["label"] = "餐桌 2" },
			[15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["label"] = "控制台 H 桌" },
			[16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["label"] = "凳子?" },
			[17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["label"] = "櫃台桌" },
			[18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["label"] = "桌子 2" },
			[19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["label"] = "電視桌" },
			[20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["label"] = "高電視桌" },
			[21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["label"] = "中等咖啡桌" },
			[22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["label"] = "中等書桌" },
			[23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["label"] = "遊艇桌子 1" },
			[24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["label"] = "遊艇桌子 2" },
			[25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["label"] = "遊艇桌子 3" },
			[26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["label"] = "CSR 桌子" },
			[27] = { ["object"] = "v_res_mconsoletrad", ["price"] = 250, ["label"] = "高邊桌" },
			[28] = { ["object"] = "v_ilev_liconftable_sml", ["price"] = 500, ["label"] = "辦公桌" },
			[29] = { ["object"] = "v_ret_tablesml", ["price"] = 350, ["label"] = "邊桌 Marillaux" },
			[30] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 500, ["label"] = "咖啡桌 Brown" },
			[31] = { ["object"] = "apa_mp_h_yacht_side_table_01", ["price"] = 300, ["label"] = "邊桌 Brown" },
			[32] = { ["object"] = "apa_mp_h_yacht_side_table_02", ["price"] = 300, ["label"] = "圓形邊桌" },
			[33] = { ["object"] = "apa_mp_h_tab_sidelrg_04", ["price"] = 300, ["label"] = "圓形邊桌 2" },
			[34] = { ["object"] = "v_club_vu_table", ["price"] = 300, ["label"] = "蓋著的桌子" },
			[35] = { ["object"] = "apa_mp_h_tab_sidelrg_07", ["price"] = 500, ["label"] = "咖啡桌玻璃" },
			[36] = { ["object"] = "bkr_prop_weed_table_01b", ["price"] = 100, ["label"] = "拍桌" },
			[37] = { ["object"] = "ba_prop_int_trad_table", ["price"] = 300, ["label"] = "展示桌" },
			[38] = { ["object"] = "apa_mp_h_str_sideboards_02", ["price"] = 750, ["label"] = "玻璃邊桌" },
			[39] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 750, ["label"] = "現代咖啡桌" },
			[40] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 1000, ["label"] = "晚餐桌玻璃" },
			[41] = { ["object"] = "xm_prop_base_staff_desk_01", ["price"] = 5000, ["label"] = "書桌 + 裝置" },
			[42] = { ["object"] = "apa_mp_h_tab_coffee_07", ["price"] = 1000, ["label"] = "三角形邊桌" },
			[43] = { ["object"] = "apa_mp_h_tab_coffee_08", ["price"] = 1000, ["label"] = "白色邊桌" },
			[44] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "玻璃邊桌" },
			[45] = { ["object"] = "apa_mp_h_tab_sidelrg_02", ["price"] = 1000, ["label"] = "玻璃邊桌 2" },
			[46] = { ["object"] = "apa_mp_h_tab_sidesml_01", ["price"] = 1000, ["label"] = "可摺疊桌" },
			[47] = { ["object"] = "ba_prop_int_edgy_table_01", ["price"] = 500, ["label"] = "大理石桌子" },
			[48] = { ["object"] = "ba_prop_int_edgy_table_02", ["price"] = 500, ["label"] = "大理石高桌" },
			[49] = { ["object"] = "apa_mp_h_tab_sidelrg_01", ["price"] = 1000, ["label"] = "玻璃邊桌" },
			[50] = { ["object"] = "xm_prop_lab_desk_01", ["price"] = 1000, ["label"] = "實驗室桌" },
		},
	},
	["plants"] = {
		label = "植栽",
		items = {
			[1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["label"] = "植物纖維" },
			[2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["label"] = "植物炸彈" },
			[3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["label"] = "花卉植物" },
			[4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["label"] = "中國花瓶" },
			[5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["label"] = "香蕉植物" },
			[6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["label"] = "棕櫚植物" },
			[7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["label"] = "棕櫚植物 2" },
			[8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["label"] = "花卉瓮" },
			[9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["label"] = "橡膠植物" },
			[10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["label"] = "植物" },
			[11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["label"] = "樹木植物" },
			[12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["label"] = "盆栽" },
			[13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["label"] = "花朵" },
			[14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["label"] = "花朵 1" },
			[15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["label"] = "花朵 2" },
			[16] = { ["object"] = "v_res_m_vasefresh", ["price"] = 300, ["label"] = "鮮花花瓶" },
			[17] = { ["object"] = "v_res_rosevasedead", ["price"] = 300, ["label"] = "粉紅花瓶 2" },
			[18] = { ["object"] = "v_res_exoticvase", ["price"] = 300, ["label"] = "鮮花花瓶 2" },
			[19] = { ["object"] = "v_res_rosevase", ["price"] = 300, ["label"] = "粉紅花瓶" },
			[20] = { ["object"] = "prop_pot_plant_6a", ["price"] = 300, ["label"] = "懸掛式植物" },
			[21] = { ["object"] = "prop_pot_plant_02a", ["price"] = 300, ["label"] = "花盆" },
			[22] = { ["object"] = "apa_mp_h_acc_plant_palm_01", ["price"] = 300, ["label"] = "棕櫚植物" },
			[23] = { ["object"] = "prop_plant_interior_05a", ["price"] = 300, ["label"] = "花盆盒" },
			[24] = { ["object"] = "prop_plant_int_01a", ["price"] = 300, ["label"] = "植物" },
			[25] = { ["object"] = "prop_plant_int_01b", ["price"] = 300, ["label"] = "植物 2" },
			[26] = { ["object"] = "prop_plant_int_02a", ["price"] = 300, ["label"] = "植物 3" },
			[27] = { ["object"] = "prop_plant_int_02b", ["price"] = 300, ["label"] = "植物 4" },
			[28] = { ["object"] = "prop_plant_int_03a", ["price"] = 300, ["label"] = "植物 5" },
			[29] = { ["object"] = "prop_plant_int_03b", ["price"] = 300, ["label"] = "植物 6" },
			[30] = { ["object"] = "prop_plant_int_03c", ["price"] = 300, ["label"] = "植物 7" },
			[31] = { ["object"] = "prop_plant_int_04a", ["price"] = 300, ["label"] = "植物 8" },
			[32] = { ["object"] = "prop_plant_int_04c", ["price"] = 300, ["label"] = "植物 9" },
			[33] = { ["object"] = "prop_plant_int_05b", ["price"] = 300, ["label"] = "花盆盒 2" },
			[34] = { ["object"] = "prop_pot_plant_01a", ["price"] = 300, ["label"] = "植物盆 2" },
			[35] = { ["object"] = "prop_pot_plant_01b", ["price"] = 300, ["label"] = "植物盆 3" },
			[36] = { ["object"] = "prop_pot_plant_01c", ["price"] = 300, ["label"] = "植物盆 4" },
			[37] = { ["object"] = "prop_pot_plant_01d", ["price"] = 300, ["label"] = "植物盆 5" },
			[38] = { ["object"] = "prop_pot_plant_01e", ["price"] = 300, ["label"] = "植物盆 6" },
			[39] = { ["object"] = "prop_pot_plant_03b", ["price"] = 300, ["label"] = "植物盆 7" },
			[40] = { ["object"] = "prop_pot_plant_05a", ["price"] = 300, ["label"] = "植物盆 8" },
			[41] = { ["object"] = "prop_pot_plant_05b", ["price"] = 300, ["label"] = "植物盆 9" },
			[42] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 300, ["label"] = "植物盆 10" },
			[43] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 300, ["label"] = "植物盆 11" },
			[44] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 300, ["label"] = "植物盆 12" },
			[45] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 300, ["label"] = "植物盆 13" },
			[46] = { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 300, ["label"] = "植物盆 14" },
			[47] = { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 300, ["label"] = "植物盆 15" },
		},
	},
	["kitchen"] = {
		label = "廚房物品",
		items = {
			[1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["label"] = "洗衣機 1" },
			[2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["label"] = "洗衣機 2" },
			[3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["label"] = "洗衣機 3" },
			[4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["label"] = "洗衣籃" },
			[5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["label"] = "冰箱 1" },
			[6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["label"] = "冰箱 2" },
			[7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["label"] = "冰箱 3" },
			[8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["label"] = "冰箱 4" },
			[9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["label"] = "爐灶" },
			[10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["label"] = "微波爐 1" },
			[11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["label"] = "微波爐 2" },
			[12] = { ["object"] = "prop_wok", ["price"] = 150, ["label"] = "炒鍋" },
			[13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["label"] = "蛋糕盤" },
			[14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["label"] = "砧板" },
			[15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["label"] = "餐具" },
			[16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["label"] = "研磨杵" },
			[17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["label"] = "廁紙 1" },
			[18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["label"] = "廁紙 2" },
			[19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["label"] = "鍋子 1" },
			[20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["label"] = "鍋子 2" },
			[21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["label"] = "鍋子 3" },
			[22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["label"] = "鍋子 4" },
			[23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["label"] = "鍋子 5" },
			[24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["label"] = "鍋子 6" },
			[25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["label"] = "鍋子 7" },
			[26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["label"] = "鍋具掛架" },
			[27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["label"] = "榨汁機" },
			[28] = { ["object"] = "v_res_ovenhobmod", ["price"] = 1000, ["label"] = "爐灶" },
			[29] = { ["object"] = "v_res_mkniferack", ["price"] = 100, ["label"] = "刀架" },
			[30] = { ["object"] = "v_res_mchopboard", ["price"] = 100, ["label"] = "砧板" },
			[31] = { ["object"] = "prop_cs_kitchen_cab_l", ["price"] = 750, ["label"] = "廚櫃 寬" },
			[32] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "廚櫃 小" },
			[33] = { ["object"] = "prop_cs_kitchen_cab_r", ["price"] = 500, ["label"] = "廚櫃 小" },
			[34] = { ["object"] = "v_res_tre_fridge", ["price"] = 500, ["label"] = "冰箱" },
			[35] = { ["object"] = "apa_mp_h_acc_coffeemachine_01", ["price"] = 500, ["label"] = "咖啡機" },
			[36] = { ["object"] = "p_new_j_counter_02", ["price"] = 500, ["label"] = "櫃台" },
			[37] = { ["object"] = "prop_bar_pump_09", ["price"] = 500, ["label"] = "泵 1" },
			[38] = { ["object"] = "prop_bar_pump_01", ["price"] = 500, ["label"] = "泵 2" },
			[39] = { ["object"] = "prop_chip_fryer", ["price"] = 500, ["label"] = "炸薯條機" },
			[40] = { ["object"] = "prop_cleaver", ["price"] = 500, ["label"] = "刀" },
			[41] = { ["object"] = "prop_coffee_mac_02", ["price"] = 500, ["label"] = "咖啡機" },
			[42] = { ["object"] = "prop_coffee_mac_01", ["price"] = 500, ["label"] = "咖啡機 2" },
			[43] = { ["object"] = "prop_cs_fork", ["price"] = 500, ["label"] = "叉子" },
			[44] = { ["object"] = "prop_cs_sink_filler", ["price"] = 500, ["label"] = "水龍頭" },
			[45] = { ["object"] = "prop_toaster_01", ["price"] = 500, ["label"] = "烤麵包機" },
			[46] = { ["object"] = "prop_cs_plate_01", ["price"] = 500, ["label"] = "盤子" },
			[47] = { ["object"] = "prop_foodprocess_01", ["price"] = 500, ["label"] = "食物處理器" },
			[48] = { ["object"] = "prop_food_sugarjar", ["price"] = 500, ["label"] = "糖罐" },
			[49] = { ["object"] = "prop_juice_dispenser", ["price"] = 500, ["label"] = "果汁機" },
			[50] = { ["object"] = "prop_knife_stand", ["price"] = 500, ["label"] = "刀座" },
			[51] = { ["object"] = "prop_knife", ["price"] = 500, ["label"] = "刀 2" },
			[52] = { ["object"] = "prop_micro_04", ["price"] = 500, ["label"] = "微波爐 4" },
			[53] = { ["object"] = "v_ret_fh_plate3", ["price"] = 500, ["label"] = "盤子 5" },
			[54] = { ["object"] = "v_ilev_tt_plate01", ["price"] = 500, ["label"] = "盤子 6" },
			[55] = { ["object"] = "v_res_fa_grater", ["price"] = 500, ["label"] = "磨碎器" },
			[56] = { ["object"] = "v_res_tt_pizzaplate", ["price"] = 500, ["label"] = "比薩盤" },
			[57] = { ["object"] = "v_ret_247_ketchup2", ["price"] = 500, ["label"] = "番茄醬" },
		},
	},
	["bathroom"] = {
		label = "廁所物品",
		items = {
			[1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["label"] = "馬桶 1" },
			[2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["label"] = "馬桶 2" },
			[3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["label"] = "馬桶 3" },
			[4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["label"] = "洗手台 1" },
			[5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["label"] = "洗手台 2" },
			[6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["label"] = "洗手台 3" },
			[7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["label"] = "洗手台 4" },
			[8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["label"] = "肥皂分配器" },
			[9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["label"] = "淋浴架" },
			[10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["label"] = "吹風機 1" },
			[11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["label"] = "吹風機 2" },
			[12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["label"] = "毛巾架 1" },
			[13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["label"] = "毛巾架 2" },
			[14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["label"] = "毛巾 1" },
			[15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["label"] = "毛巾 2" },
			[16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["label"] = "毛巾 3" },
			[17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["label"] = "浴缸" },
			[18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["label"] = "洗手台" },
			[19] = { ["object"] = "v_ilev_mm_faucet", ["price"] = 100, ["label"] = "水龍頭" },
			[20] = { ["object"] = "v_res_tre_washbasket", ["price"] = 250, ["label"] = "洗衣籃" },
			[21] = { ["object"] = "prop_toilet_soap_02", ["price"] = 100, ["label"] = "盤子肥皂" },
			[22] = { ["object"] = "prop_bar_sink_01", ["price"] = 100, ["label"] = "洗手台" },
			[23] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 1000, ["label"] = "浴缸" },
			[24] = { ["object"] = "prop_toilet_brush_01", ["price"] = 1000, ["label"] = "刷子" },
			[25] = { ["object"] = "prop_toilet_roll_01", ["price"] = 1000, ["label"] = "衛生紙卷" },
			[26] = { ["object"] = "prop_toilet_roll_02", ["price"] = 1000, ["label"] = "衛生紙卷 2" },
			[27] = { ["object"] = "prop_toilet_shamp_01", ["price"] = 1000, ["label"] = "洗髮水" },
			[28] = { ["object"] = "prop_toilet_shamp_02", ["price"] = 1000, ["label"] = "洗髮水 2" },
		},
	},
	["medical"] = {
		label = "醫療用品",
		items = {
			[1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["label"] = "酒桶" },
			[2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["label"] = "猿猴箱" },
			[3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["label"] = "大型猿猴箱" },
			[4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["label"] = "床 1" },
			[5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["label"] = "床 2" },
			[6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["label"] = "床邊桌" },
			[7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["label"] = "長凳 1" },
			[8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["label"] = "長凳 2" },
			[9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["label"] = "中央長凳" },
			[10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["label"] = "長凳組" },
			[11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["label"] = "大桌" },
			[12] = { ["object"] = "v_med_bin", ["price"] = 150, ["label"] = "垃圾桶" },
			[13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["label"] = "離心機" },
			[14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["label"] = "冷卻器" },
			[15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["label"] = "監視器" },
			[16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["label"] = "剖檢桌" },
			[17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["label"] = "垃圾桶" },
			[18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["label"] = "手推車" },
			[19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["label"] = "化學品" },
			[20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["label"] = "標本桌" },
			[21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["label"] = "文件盒" },
			[22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["label"] = "文件櫃" },
			[23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["label"] = "水管" },
			[24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["label"] = "大櫃" },
			[25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["label"] = "燈箱" },
			[26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["label"] = "醫用凳" },
			[27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["label"] = "小冰箱" },
			[28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["label"] = "廁紙" },
			[29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["label"] = "影印機" },
			[30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["label"] = "電視櫃" },
			[31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["label"] = "牆上櫃" },
			[32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["label"] = "檢查燈" },
			[33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["label"] = "氣罐" },
			[34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["label"] = "危險物掃描器" },
			[35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["label"] = "頭部牆" },
			[36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["label"] = "座椅" },
			[37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["label"] = "醫療桌" },
			[38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["label"] = "手套盒" },
			[39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["label"] = "廢物桶" },
			[40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["label"] = "振盪器" },
			[41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["label"] = "急救包" },
		},
	},
	["walldecoration"] = {
		label = "牆壁裝飾",
		items = {
			[1] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 1000, ["label"] = "有痕跡的畫" },
			[2] = { ["object"] = "v_ind_cs_toolboard", ["price"] = 500, ["label"] = "工具板" },
			[3] = { ["object"] = "apa_mp_stilts_bed_art", ["price"] = 300, ["label"] = "3D 藝術" },
			[4] = { ["object"] = "ex_office_swag_paintings03", ["price"] = 1000, ["label"] = "地面畫" },
			[5] = { ["object"] = "ex_mp_h_acc_artwallm_03", ["price"] = 750, ["label"] = "抽象畫" },
			[6] = { ["object"] = "ex_p_h_acc_artwallm_04", ["price"] = 750, ["label"] = "抽象畫 2" },
			[7] = { ["object"] = "ex_p_h_acc_artwalll_01", ["price"] = 1250, ["label"] = "大型抽象畫" },
			[8] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 750, ["label"] = "抽象畫 3" },
			[9] = { ["object"] = "ex_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "抽象畫 4" },
			[10] = { ["object"] = "ex_p_h_acc_artwallm_03", ["price"] = 750, ["label"] = "抽象畫 5" },
			[11] = { ["object"] = "apa_mp_stilts_a_study_pics", ["price"] = 500, ["label"] = "畫作" },
			[12] = { ["object"] = "apa_mp_h_acc_artwallm_02", ["price"] = 750, ["label"] = "抽象畫 6" },
			[13] = { ["object"] = "apa_mp_h_acc_artwalll_02", ["price"] = 750, ["label"] = "抽象畫 7" },
			[14] = { ["object"] = "apa_mp_h_acc_artwallm_04", ["price"] = 750, ["label"] = "抽象畫 8" },
			[15] = { ["object"] = "prop_dart_bd_cab_01", ["price"] = 250, ["label"] = "飛鏢板" },
			[16] = { ["object"] = "prop_dart_bd_01", ["price"] = 250, ["label"] = "飛鏢板 2" },
			[17] = { ["object"] = "hei_heist_acc_artwalll_01", ["price"] = 250, ["label"] = "牆上裝飾 1" },
			[18] = { ["object"] = "hei_heist_acc_artgolddisc_01", ["price"] = 250, ["label"] = "牆上裝飾 2" },
			[19] = { ["object"] = "hei_heist_acc_artgolddisc_02", ["price"] = 250, ["label"] = "牆上裝飾 3" },
			[20] = { ["object"] = "hei_heist_acc_artgolddisc_03", ["price"] = 250, ["label"] = "牆上裝飾 4" },
			[21] = { ["object"] = "hei_heist_acc_artgolddisc_04", ["price"] = 250, ["label"] = "牆上裝飾 5" },
			[22] = { ["object"] = "v_ilev_ra_doorsafe", ["price"] = 250, ["label"] = "豪華裝飾" },
		},
	},
}
